  /**
 * Generated by GraphQL Monster Builder (GMB) version: __VERSION__
 *     Do NOT edit! For more info see: https://github.com/miuan/graphql-monster-builder
 */
  // templates/service-transform-one-id.ts
  // case where data._MEMBER_NAME_ have multiple ids or multiple object
  if (data._PAYLOAD_NAME_FOR_ID_) {
    _LINKDED_IDS_.push(data._PAYLOAD_NAME_FOR_ID_);
    data._MEMBER_NAME_ = data._PAYLOAD_NAME_FOR_ID_
  } 
